name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app  # Xcode'u ayarlar.

    - name: Install dependencies
      run: pod install --repo-update  # Eğer CocoaPods kullanıyorsanız, bağımlılıkları kurar.

    - name: Build
      run: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive  # Projeyi derler ve bir arşiv oluşturur.

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build  # IPA dosyasını dışa aktarır.

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: app-release.ipa  # IPA dosyasının adı.
        path: build/app-release.ipa  # .ipa dosyasının bulunduğu yol.
